### ISSUE TITLE
Deprecate lcdClientMock

### ISSUE THREAD

**Issue by fedekunze** [luniehq/lunie#1742]
- the mocked LCDClient supports the demo mode, which is not being used even by Voyager. 
- it takes a lot of development time to copy the same behaviour from Gaia into the lcdClientMock (specially POST requests)
   - use contract tests for that

Scope:

- [ ] replace mocked values used by unit tests for swagger file values
- [x] Deprecate demo mode
- [ ] Delete `lcdClientMock.js`

**Comment by jbibla** [comment]
please include a description of why

**Comment by fedekunze** [comment]
the main a reason was bc the mocked LCDClient supports the demo mode, which is not being used even by us. The second reason was bc it takes a lot of development time to copy the same behaviour from Gaia into the lcdClientMock (specially POST requests) and for that we can just use contract tests.

We talked about this on the retro yesterday but please feel free to add a `discuss` label it you think it needs more sync discussion

**Comment by jbibla** [comment]
thanks for the explanation! fabo mentioned to me in our call yesterday - makes sense!
