### ISSUE TITLE
Add e2e tests for all actions

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#2231]
**Is your feature request related to a problem? Please describe.**

As a user
I want the developers to test the main actions in e2e tests to prevent them from producing breaking bugs
So that I have a working UI at all time.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

AC:
@faboweb 
- [x] have e2e test for sending coins
- [x]  have e2e test for delegating
- [x]  have e2e test for undelegating
- [x]  have e2e test for redelegating
@colw
- [ ]  have e2e test for creating a proposal
- [ ]  have e2e test for depositing on a proposal
- [ ]  have e2e test for voting on a proposal
- [ ] have e2e tests for withdrawing rewards from single and multiple validators
