### ISSUE TITLE
User Accounts M1

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#4237]
Remake of luniehq/lunie-api#789 (the repo got archived so we cannot comment there anymore)

We want to be able to block users from using the notifications feature if they are not locked in with an email.

AC

- [x] Provide sign up ability
- [x] Provide sign in ability
- [x] Provide sign out ability
- [x] Provide indicator that user is signed in
- [x] Prevent users from seeing notifications if not signed in

PR

- [x] FE: Implement Firebase auth luniehq/lunie#4147
- [x] API: Store user accounts in DB #4295
- [x] FE: Implement user account indicator
- [x] FE: Implement sign up/ sign in flow
- [x] FE: Implement sign out functionality
- [x] API: Block users from seeing notifications luniehq/lunie#4149
- [ ] FE: handle not signed in users on notifications page luniehq/lunie#4148

**Comment by Bitcoinera** [comment]
I just realized there is not that much to be done here as I first though!

Like for example these two items:
```
FE: Implement sign up/ sign in flow
FE: Implement sign out functionality

```

They are already in #4242, at least the logic (yeah, styles are crap, but it's fine)

And then this other one, `FE: Implement user account indicator`, the work there was already started by @jbibla in #4275

**Comment by faboweb** [comment]
> (yeah, styles are crap, but it's fine)

the food styles should be implemented

**Comment by Bitcoinera** [comment]
> the food styles should be implemented

What are the food styles? 👀 🍔

**Comment by jbibla** [comment]
@Bitcoinera i started #4275 but you can take over - all the UI components and logic should be there - just needs to be wired up (i think).

**Comment by faboweb** [comment]
> What are the food styles? 👀 🍔

sorry, hahahah. I meant the good styles

**Comment by Bitcoinera** [comment]
> @Bitcoinera i started #4275 but you can take over - all the UI components and logic should be there - just needs to be wired up (i think).

Yes, I was looking at it. There is a CSS challenge lying in there by what I saw, which is making the popover appear relative to the position you click on. But since there are only two positions (AppHeader and App), I think I will just hack it and that's it

**Comment by Bitcoinera** [comment]
So I guess no logic right? It is nearly only a display PR

**Comment by Bitcoinera** [comment]
Ah yeah, I saw what you mean with "wire up" @jbibla

**Comment by Bitcoinera** [comment]
We can close this
