### ISSUE TITLE
Notifications System

### ISSUE THREAD

**Issue by nylira** [luniehq/lunie#891]
UI Version: 0.7.0

Description: It would be useful to have a toggleable notifications slide-out menu, so users can close notifications without losing them forever. 

- [ ] notifications button in the top right corner of the app that toggles a notifications modal, and shows a red dot with # of new notifications
- [ ] new notifications menu that takes up 100% of the screen on mobile, and 25% of the screen in desktop. It should be attached to the right side of the screen.
- [ ] allow the user to clear all notifications from the menu 
- [ ] update error notifications to disappear after a few seconds, instead of persisting forever
- [ ] send all notifications to the notifications menu after a few seconds

**Comment by nylira** [comment]
Or instead of recreating all this, we just use Electron's support for OS notifications. This would also relate directly to #808, a voyager daemon.

**Comment by faboweb** [comment]
Why not directly use web notifications? It should work from within Electron. Still there is no notification history I think. (https://electronjs.org/docs/tutorial/notifications)

**Comment by jolesbi** [comment]
> notifications button in the top right corner of the app that toggles a notifications modal, and shows a red dot with # of new notifications

this sounds great.

> new notifications menu that takes up 100% of the screen on mobile, and 25% of the screen in desktop. It should be attached to the right side of the screen.

i would prefer if this was a notifications page instead of a modal. this, like the tx history is something we would want people to be able to visit and use as a historical reference. modals tend to be more fleeting / don't imply the type of persistence i would hope for.

> allow the user to clear all notifications from the menu

hmm. maybe we need to define the types of notifications we're talking about here...
  
> update error notifications to disappear after a few seconds, instead of persisting forever

i think there is a difference between cosmos specific notifications like "one of the validators you've bonded too is no longer a validator" and console errors. should we consider cosmos-notifications being included in the tx history somehow?

> send all notifications to the notifications menu after a few seconds

i would assume that notifications would appear "on the notifications page / menu" instantly - with this kind of page perhaps we don't need the error-modals at all.

**Comment by faboweb** [comment]
> i think there is a difference between cosmos specific notifications like "one of the validators you've bonded too is no longer a validator" and console errors. should we consider cosmos-notifications being included in the tx history somehow?

Would this overload the tx history? If we overload it too much, users might get information blindness and miss critical information. This is why I tend more to a dashboard of some kind, which shows data more structured.
